# Site settings
title: 
header-img: img/home-bg.png
email: brandon@brandonleeproductions.com
copyright_name: brandong1
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  brandong1
learn_profile: brandong1
email_username: brandon@brandonleeproductions.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
